from __future__ import annotations

from arbitrage_bot.config import (
    AlertConfig,
    BacktestConfig,
    BotConfig,
    CashAndCarryPair,
    CrossExchangeRebalanceConfig,
    DcaConfig,
    ExchangeConfig,
    ExecutionAlgoConfig,
    MarketMakerConfig,
    OnchainMonitorConfig,
    OptionComboConfig,
    OptionsArbitrageConfig,
    PortfolioConfig,
    RiskConfig,
    SlowExecutionConfig,
    SpotGridConfig,
    SpotMarketConfig,
    StrategyCenterConfig,
    StrategyTimelineConfig,
    TradeLogConfig,
    WebSecurityConfig,
)


def make_config(
    *,
    market_maker: MarketMakerConfig | None = None,
    market_makers: list[MarketMakerConfig] | None = None,
    slow_execution: SlowExecutionConfig | None = None,
    spot_grid: SpotGridConfig | None = None,
    dca: DcaConfig | None = None,
    execution_algo: ExecutionAlgoConfig | None = None,
    backtest: BacktestConfig | None = None,
    options_arbitrage: OptionsArbitrageConfig | None = None,
    portfolio: PortfolioConfig | None = None,
    spot_markets: list[SpotMarketConfig] | None = None,
    spot_exchanges: list[ExchangeConfig] | None = None,
    cash_and_carry_pairs: list[CashAndCarryPair] | None = None,
    derivative_exchanges: list[ExchangeConfig] | None = None,
    option_combos: list[OptionComboConfig] | None = None,
    risk: RiskConfig | None = None,
    trade_log: TradeLogConfig | None = None,
    strategy_center: StrategyCenterConfig | None = None,
    strategy_timeline: StrategyTimelineConfig | None = None,
    alerts: AlertConfig | None = None,
    web_security: WebSecurityConfig | None = None,
    quote_rates: dict[str, float] | None = None,
    cross_exchange_rebalance: CrossExchangeRebalanceConfig | None = None,
) -> BotConfig:
    return BotConfig(
        poll_seconds=1.0,
        order_book_depth=20,
        notional_quote=200.0,
        min_profit_quote=0.1,
        min_profit_bps=1.0,
        min_basis_bps=15.0,
        common_quote_currency="USD",
        quote_rates=quote_rates or {"USD": 1.0},
        quote_rate_sources=[],
        onchain_monitor=OnchainMonitorConfig(),
        market_maker=market_maker or MarketMakerConfig(),
        market_makers=market_makers or [],
        slow_execution=slow_execution or SlowExecutionConfig(),
        spot_grid=spot_grid or SpotGridConfig(),
        dca=dca or DcaConfig(),
        execution_algo=execution_algo or ExecutionAlgoConfig(),
        backtest=backtest or BacktestConfig(),
        options_arbitrage=options_arbitrage or OptionsArbitrageConfig(),
        strategy_center=strategy_center or StrategyCenterConfig(),
        portfolio=portfolio or PortfolioConfig(),
        spot_symbols=[],
        spot_markets=spot_markets or [],
        cash_and_carry_pairs=cash_and_carry_pairs or [],
        option_combos=option_combos or [],
        spot_exchanges=spot_exchanges or [],
        derivative_exchanges=derivative_exchanges or [],
        cross_exchange_rebalance=(
            cross_exchange_rebalance or CrossExchangeRebalanceConfig()
        ),
        risk=risk or RiskConfig(),
        trade_log=trade_log or TradeLogConfig(enabled=False),
        strategy_timeline=strategy_timeline or StrategyTimelineConfig(enabled=False),
        alerts=alerts or AlertConfig(),
        web_security=web_security or WebSecurityConfig(),
    )
